{% set name = "composition_based_feature_vector" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/composition_based_feature_vector-{{ version }}.tar.gz
  sha256: a71e95c91eb83a680ecd9c862410a071c79429afddf853394f4dbf469f359f4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
    - flit
  run:
    - numpy
    - pandas
    - pytest
    - python >=3.0
    - tqdm

test:
  imports:
    - composition_based_feature_vector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/composition_based_feature_vector/
  summary: Tool for quickly creating a composition-based feature vector.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
