{% set name = "composition_based_feature_vector" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/composition_based_feature_vector-{{ version }}.tar.gz
  sha256: af30bd1acb2716e60786d70cdc3a2a2ce4a459c62aa707029b01520fad82e244

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0,<3.9
    - flit
  run:
    - numpy
    - pandas
    - pytest
    - python >=3.0,<3.9
    - tqdm

test:
  imports:
    - composition_based_feature_vector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/composition_based_feature_vector/
  summary: Tool for quickly creating a composition-based feature vector.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
